import React, { useState, useEffect } from 'react';

function App() {
  const [inputText, setInputText] = useState('');
    const [outputText, setOutputText] = useState('');
      const [inputLanguage, setInputLanguage] = useState('');
        const [outputLanguage, setOutputLanguage] = useState('');

          useEffect(() => {
              // Load the Google Assistant SDK
                  window.gapi.load('client', () => {
                        window.gapi.client.init({
                                apiKey: 'YOUR_API_KEY_HERE',
                                        discoveryDocs: ['https://assistant.google.com/discovery/rest'],
                                              }).then(() => {
                                                      // Enable Interpreter Mode
                                                              window.google.assistant.setup({
                                                                        onSpeechEnd: () => {
                                                                                    handleTranslate();
                                                                                              },
                                                                                                        onConversationFinished: () => {
                                                                                                                    setInputText('');
                                                                                                                                setOutputText('');
                                                                                                                                          },
                                                                                                                                                  });
                                                                                                                                                        });
                                                                                                                                                            });
                                                                                                                                                              }, []);

                                                                                                                                                                const handleInputLanguageChange = (event) => {
                                                                                                                                                                    setInputLanguage(event.target.value);
                                                                                                                                                                      };

                                                                                                                                                                        const handleOutputLanguageChange = (event) => {
                                                                                                                                                                            setOutputLanguage(event.target.value);
                                                                                                                                                                              };

                                                                                                                                                                                const handleTranslate = () => {
                                                                                                                                                                                    const request = {
                                                                                                                                                                                          input: { text: inputText, languageCode: 'auto' },
                                                                                                                                                                                                outputConfig: { targetLanguageCode: outputLanguage },
                                                                                                                                                                                                    };
                                                                                                                                                                                                        window.google.assistant.interpreter.translate(request, (response) => {
                                                                                                                                                                                                              setOutputText(response.output.text);
                                                                                                                                                                                                                    window.google.assistant.converse('output', { textQuery: response.output.text });
                                                                                                                                                                                                                        });
                                                                                                                                                                                                                          };

                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                      <h1>Interpreter App</h1>
                                                                                                                                                                                                                                            <label>
                                                                                                                                                                                                                                                    Select input language:
                                                                                                                                                                                                                                                            <option value={inputLanguage} onChange={handleInputLanguageChange}></option>
                                                                                                                                                                                                                                                                      <option value="">Auto-detect</option>
                                                                                                                                                                                                                                                                                <option value="af">Afrikaans</option>
                                                                                                                                                                                                                                                                                          <option value="am">Amharic</option>
                                                                                                                                                                                                                                                                                                    <option value="ar">Arabic</option>
                                                                                                                                                                                                                                                                                                              <option value="az">Azerbaijani</option>
                                                                                                                                                                                                                                                                                                                        <option value="be">Belarusian</option>
                                                                                                                                                                                                                                                                                                                                  <option value="bg">Bulgarian</option>
                                                                                                                                                                                                                                                                                                                                            <option value="bn">Bengali</option>
                                                                                                                                                                                                                                                                                                                                                      <option value="bs">Bosnian</option>
                                                                                                                                                                                                                                                                                                                                                                <option value="ca">Catalan</option>
                                                                                                                                                                                                                                                                                                                                                                          <option value="ceb">Cebuano</option>
                                                                                                                                                                                                                                                                                                                                                                                    <option value="co">Corsican</option>
                                                                                                                                                                                                                                                                                                                                                                                              <option value="cs">Czech</option>
                                                                                                                                                                                                                                                                                                                                                                                                        <option value="cy">Welsh</option>
                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="da">Danish</option>
                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="de">German</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="el">Greek</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="en">English</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="eo">Esperanto</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="es">Spanish</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="et">Estonian</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="eu">Basque</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="fa">Persian</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="fi">Finnish</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="fr">French</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="fy">Frisian</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="ga">Irish</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="gd">Scots Gaelic</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="gl">Galician</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="gu">Gujarati</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="ha">Hausa</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="haw">Hawaiian</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Select output language:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <select value={outputLanguage} onChange={handleOutputLanguageChange}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="af">Afrikaans</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="am">Amharic</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="ar">Arabic</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="az">Azerbaijani</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="be">Belarusian</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="bg">Bulgarian</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="bn">Bengali</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <option value="bs">Bosnian</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="ca">Catalan</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <option value="ceb">Cebuano</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="co">Corsican</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="cs">Czech</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="cy">Welsh</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="da">Danish</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="de">German</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </select>  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label>  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Enter text to translate:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <textarea rows={4} cols={50} value={inputText} onChange={(e) => setInputText(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label>  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Translated text:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <textarea rows={4} cols={50} disabled value={outputText} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }  

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default App;